name: Trigger QA Build
on:
  issue_comment:
    types: [created]
    branches-ignore:
      - 'master'
      - 'release**'
      - 'integration**'
      - 'uat**'
jobs:
  qa-deployment:
    name: QA Build
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/deploy')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'anandrikka/gh-actions'
          ref: 'refs/tags/main'
          path: './.github/actions'
#          ssh-key: ${{ secrets.SS_GHA_SSH }}
      - uses: ./.github/actions/issue-ops
        id: issue-ops-deploy
        with:
          trigger: '/deploy'
          environments: qa1,qa2,qa3,qa4,qa5,qa6
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to QA
        if: ${{ steps.issue-ops-deploy.outputs.deploy_env != '' }}
        uses: ./.github/actions/cci-workflow
        with:
          cci_token: ${{ secrets.CIRCLECI_DISPATCH_TOKEN }}
          branch: ${{ steps.issue-ops-deploy.outputs.deploy_ref }}
          request_params: |
            workflow_name:gha_qa_deploy
            deploy_env:${{steps.issue-ops-deploy.outputs.deploy_env}}
            deploy_aws_region:us-east-2
            deploy_aws_env:${{steps.issue-ops-deploy.outputs.deploy_env}}
            gha_deployment_id:${{steps.issue-ops-deploy.outputs.deployment_id}}
